name: Unit
description: Performs unit tests checks
runs:
  using: composite
  steps:
    - run: npm run build
      shell: bash
    - run: npm -w packages/core test
      shell: bash
    - run: npm -w packages/dom test
      shell: bash
    - run: npm -w packages/react-dom test
      shell: bash
    - run: npm -w packages/react test
      shell: bash
    - run: npm -w packages/vue test
      shell: bash
