name: Functional
description: Performs functional tests checks
runs:
  using: composite
  steps:
    - run: npx playwright install --with-deps chromium
      shell: bash
    - run: npm run build
      shell: bash
    - run: npm run test:functional -- --update-snapshots
      shell: bash
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: visual-snapshots-diff
        path: test-results
